apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: backescape/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.js"
                    dest: .
        - image: backescape/comments
          context: comments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: backescape/event-bus
          context: event-bus
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: backescape/moderation
          context: moderation
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: backescape/posts
          context: posts
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
        - image: backescape/query
          context: query
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "*.js"
                    dest: .
